(() => {
  let flowData = { waters: {} };
  window.cofishHasStreamflow=water=>Boolean(flowData.waters?.[water?.key]);
  const loaded = fetch('data/streamflow.json').then(response => response.ok ? response.json() : Promise.reject(new Error(response.statusText))).then(data => { flowData = data; window.render?.(); return data; }).catch(error => { console.warn('Stream-flow data unavailable', error); return flowData; });
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const flowValue = value => Number.isFinite(Number(value)) ? Number(value).toLocaleString(undefined,{maximumFractionDigits:1}) : '—';
  function measuredAt(value){if(!value)return'Time unavailable';const date=new Date(value);return Number.isNaN(date.getTime())?'Time unavailable':date.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
  function trendSvg(points){const usable=(points||[]).map(point=>({date:point.date,value:Number(point.value)})).filter(point=>Number.isFinite(point.value));if(usable.length<2)return'<p class="streamflow-empty">A 30-day trend is not available for this station yet.</p>';const values=usable.map(point=>point.value),min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min);const coords=usable.map((point,index)=>`${(index/(usable.length-1)*100).toFixed(1)},${(32-(point.value-min)/range*28).toFixed(1)}`).join(' ');const path=coords.split(' ').join(' L ');return `<div class="streamflow-chart"><svg viewBox="0 0 100 36" preserveAspectRatio="none" role="img" aria-label="30-day stream flow trend"><path class="streamflow-area" d="M ${path} L 100,36 L 0,36 Z"></path><polyline points="${coords}"></polyline></svg><div><span>${escapeHtml(usable[0].date)}</span><span>${escapeHtml(usable.at(-1).date)}</span></div></div>`}
  function card(water){const flow=flowData.waters?.[water.key];if(!flow)return'';const station=flow.station||{},current=flow.current||{},status=[current.flag,current.review_status].filter(Boolean).join(' · '),officialUrl=station.official_url||flowData.source_url;return `<section class="streamflow-card"><div class="streamflow-heading"><div><p>STREAM FLOW</p><h3>${flowValue(current.value)} <small>${escapeHtml(current.units||'cfs')}</small></h3></div><span>Updated ${escapeHtml(measuredAt(current.measured_at))}</span></div>${trendSvg(flow.trend)}<div class="streamflow-meta"><p><strong>${escapeHtml(station.name||station.water_source)}</strong></p><p>${Number(station.distance_miles).toFixed(1)} mi from mapped water${status?` · ${escapeHtml(status)}`:''}</p></div><a href="${escapeHtml(officialUrl)}" target="_blank" rel="noreferrer">View official DWR station ↗</a><p class="streamflow-note">Gauge readings are provisional and describe conditions at the station, which may differ elsewhere on this water.</p></section>`}
  const originalDetailHtml=window.detailHtml;
  window.detailHtml=function streamflowDetailHtml(water){const html=originalDetailHtml(water),flowCard=card(water);return flowCard?html.replace('<h3>Water details</h3>',`${flowCard}<h3>Water details</h3>`):html};
  const originalShowDetails=window.showDetails;
  window.showDetails=function streamflowShowDetails(water){originalShowDetails(water);const content=document.getElementById('detailContent');if(content&&!content.querySelector('.streamflow-card')){const flowCard=card(water);if(flowCard){const heading=[...content.querySelectorAll('h3')].find(element=>element.textContent==='Water details');heading?.insertAdjacentHTML('beforebegin',flowCard)}}};
  window.cofishStreamflow={loaded,card};
})();
